# -*- coding: utf-8 -*-
"""MobileNet-v1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/126M87nwtWGSX0MKBf8IH0miliFPLzg-W
"""

from tensorflow.keras.layers import Input , ReLU , Conv2D , DepthwiseConv2D , BatchNormalization , Dense , Flatten , AveragePooling2D
from tensorflow.keras import Model

INPUT_SHAPE = (224,224,3) 
NUM_OF_CLASSES = 1000

def mobile_net_block(x ,filters , strides) : 
  x = DepthwiseConv2D(kernel_size=3 , strides=strides , padding="same")(x)
  x = BatchNormalization()(x)
  x = ReLU()(x)

  x = Conv2D(filters=filters , kernel_size=1 , strides=1 , padding="same")(x)
  x = BatchNormalization()(x)
  x = ReLU()(x)
  return x

INPUTS = Input(INPUT_SHAPE)
x = Conv2D(filters=32 , kernel_size=3 , strides=2 , padding="same")(INPUTS)
x = BatchNormalization()(x)
x = ReLU()(x)

x = mobile_net_block(x , filters=64 , strides=1)
x = mobile_net_block(x , filters=128 , strides=2)
x = mobile_net_block(x , filters=128 , strides=1)

x = mobile_net_block(x , filters=256 , strides=2)
x = mobile_net_block(x , filters=256 , strides=1)

x = mobile_net_block(x , filters=512 , strides=2)

for _ in range(5):
  x = mobile_net_block(x , filters=512 , strides=1)

x = mobile_net_block(x , filters=1024 , strides=2)
x = mobile_net_block(x , filters=1024 , strides=1)

x = AveragePooling2D(pool_size=7 , strides=1)(x)

OUTPUTS = Dense(units=NUM_OF_CLASSES , activation="softmax")(x)
model = Model(inputs=INPUTS , outputs=OUTPUTS)

model.summary()